### ISSUE TITLE
Statemachine editor does not have scroll bars

### ISSUE THREAD

**Issue by skohlbr** [pschillinger/flexbe_chrome_app#8]
It appears that large (and/or clumsily layouted) state machines cannot be manipulated easily because they exceed the space of the editor and there are no scrollbars appearing. Is there a method (keyboard shortcuts or similar) for scrolling? Can scroll bar functionality be added?

**Comment by pschillinger** [comment]
There is no such method available in the editor right now. But I can look into adding scrollbars.

In general I would rather prefer something like pan and zoom for the editor, but unfortunately, that's not really possible with the drawing framework I use.

How urgent do you need it? I assume you refer to synthesis results, at least that's the typical case for large and clumsy state machines. In this case, generated states can be arranged by setting their [position](https://github.com/team-vigir/flexbe_behavior_engine/blob/master/flexbe_msgs/msg/StateInstantiation.msg#L44), maybe this helps in the meantime.

**Comment by spmaniato** [comment]
If I remember correctly, another typical case is when you compose and save a state machine on a large monitor and then open it later on a much smaller screen (e.g. on a laptop)

**Comment by pschillinger** [comment]
Right, this can also be a problem.

Quick update: There won't be scrollbars, but panning will come with one of the next updates.

**Comment by pschillinger** [comment]
Panning is available in the `develop` branch (you can manually download and update: [Version 1.0.15](https://github.com/pschillinger/flexbe_chrome_app/blob/ad3b78ef9bbd94976c6cf6d6ab35cbfb08db5f97/FlexBE.crx?raw=true)).

It works by holding down `shift` and then dragging around over the background. If you press `space` while holding down `shift`, the view will jump back to the origin. Same happens when opening a new container.
